# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: contactform
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  apiGateway:
      shouldStartNameWithService: true
      apiKeys:
        - name: developer-key
          value: test2qwadfdasfhsjfsu3234
      binaryMediaTypes:
      - 'image/png'
      - 'text/txt'

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1
  # name, runtimeなどの記述は省略
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/usersTable1"
        - Effect: "Allow"
          Action:
            - s3:PutObject
          Resource: "arn:aws:s3:::buckettsubasatest"



# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.py'
#    - '!exclude-me-dir/**'
#    - include-me.py
#    - include-me-dir/**

functions:
  test:
    handler: test.test
    events:
      - http:
          path: /test
          method: post
          private: true
          cors: true

  fileupload:
    handler: upload.upload
    events:
      - http:
          path: /upload
          method: post
          private: true
          cors: true
      - s3:
          bucket: buckettsubasatest
          event: s3:ObjectCreated:*
          existing: true 

  get-contact:
    handler: handler.get_contact_index
    events:
      - http:
          path: /contact/{id}
          method: get
          private: true
          cors: true
  post-contact:
    handler: handler.post_contact_index
    events:
      - http:
          path: /contact
          method: post
          private: true
          cors: true
  put-contact:
    handler: handler.put_contact_index
    events:
      - http:
          path: /contact/{id}
          method: put
          private: true
          cors: true
  delete-contact:
    handler: handler.delete_contact_index
    events:
      - http:
          path: /contact/{id}
          method: delete
          private: true
          cors: true

resources:
 - ${file(serverless-dynamodb.yml)}
 - ${file(serverless-s3.yml)}












#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - httpApi:
#          path: /users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
